version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - bodyclose
    - gosec
    - misspell
    - sqlclosecheck
    - staticcheck
    - unconvert
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
