name: Build, lint, and test
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.24
          cache: true

      - uses: golangci/golangci-lint-action@v8.0.0
        with:
          version: v2.1.0
          args: --timeout 5m

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.24
          cache: true

      - run: make test
